main:
  - name: Biográfia
    url: "#about"
    weight: 10
  - name: Szakismeret
    url: "#skills"
    weight: 30
  - name: Tapasztalat
    url: "#experience"
    weight: 30
  - name: Elért eredmények
    url: "#accomplishments"
    weight: 40
  - name: Projektek
    url: "#projects"
    weight: 50
  - name: Kontakt
    url: "#contact"
    weight: 60
